# Список заголовков задач, которые будут отслеживаться
# Система будет обрабатывать только задачи с этими заголовками
task_titles:
  - "Отключил сервер"                    # Пример: задачи по отключению серверов
  - "Отключил промежуточную точку"       # Пример: задачи по отключению промежуточных точек
  # Добавьте свои заголовки задач для мониторинга

# Сопоставление пользователей Wrike с Telegram-упоминаниями
# Формат: "Имя в Wrike": "Отображение в Telegram"
user_names:
  IT: "IT: @Group"                    # Группа IT получает уведомления
  DR: "DR: @Drop"                     # Группа DR получает уведомления  
  "Name lastname": "Name lastname"    # Индивидуальные пользователи
  # Добавьте соответствия для ваших пользователей

# Перевод уровней важности с английского на русский
importance_translation:
  High: "Высокая"      # Высокая важность
  Normal: "Обычная"    # Обычная важность
  Low: "Низкая"        # Низкая важность

# Слова, которые будут заменены на эмоджи в комментариях
synonyms:
  # Слова, которые будут заменены на ✅ (включение/подключение)
  include:
    - "Вкл"
    - "Вклю"
    - "Включ"
    - "Включи"
    - "Включил"
    - "Включили"
    - "Включение"
    - "Включены"
    - "Включено"
    - "Включила"
    - "Включала"
    - "Включали"
    - "Подкл"
    - "Подклю"
    - "Подключ"
    - "Подключи"
    - "Подключил"
    - "Подключены"
    - "Подключили"
    - "Подключено"
    - "Подключила"
    - "Подключала"
    - "Подключали"
    - "Вклюил"        # Опечатки (для надежности)
    - "Подклюил"      # Опечатки (для надежности)
    
  # Слова, которые будут заменены на 🔥 (выключение/отключение)
  exclude:
    - "Выкл"
    - "Выклю"
    - "Выключ"
    - "Выключи"
    - "Выключил"
    - "Выключили"
    - "Выключено"
    - "Выключены"
    - "Выключила"
    - "Выключала"
    - "Выключали"
    - "Откл"
    - "Отклю"
    - "Отключ"
    - "Отключи"
    - "Отключил"
    - "Отключили"
    - "Отключено"
    - "Отключены"
    - "Отключила"
    - "Отключала"
    - "Отключали"
    - "Отклюил"
    - "Выклюил"
    - "Откючила"

# ===========================================
# НАСТРОЙКИ КЭШИРОВАНИЯ
# ===========================================

# Кэширование данных Wrike для уменьшения нагрузки на API
cache_settings:
  projects_ttl: 172800    # Время жизни кэша проектов (48 часов = 172800 секунд)
  users_ttl: 172800       # Время жизни кэша пользователей (48 часов = 172800 секунд)
  max_size: 100           # Максимальное количество элементов в кэше

# ===========================================
# НАСТРОЙКИ ЛОГИРОВАНИЯ
# ===========================================

# Настройка уровней логирования и форматов
logging_settings:
  level: INFO                   # Доступные уровни: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: json                  # Доступные форматы: json, text
  handlers:                     # Настройки обработчиков
    file:                       # Настройки файлового обработчика логов
      enabled: true             # включает запись логов в файл
      filename: "logging/webhook.log"   # Имя лог-файла
      max_size_mb: 10           # Максимальный размер лог-файла в мегабайтах
      backup_count: 5           # Количество резервных лог-файлов
    console:                    # Настройки консольного обработчика
      enabled: true
  fields:                       # Дополнительные поля для лог-файла
    app_name: "wrike_webhook"   # Идентификатор приложения в логах
    environment: "production"   # Среда разработки

# ===========================================
# НАСТРОЙКИ АДМИН-ПАНЕЛИ
# ===========================================

# Логин и пароль для доступа к админ-панели
# ВАЖНО: Обязательно измените логин и пароль по умолчанию!
admin_panel:
  username: "admin"       # Логин для доступа к админ-панели (ОБЯЗАТЕЛЬНО ИЗМЕНИТЕ!)
  password: "admin"       # Пароль для доступа к админ-панели (ОБЯЗАТЕЛЬНО ИЗМЕНИТЕ!)